[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# These tests can only be run in zksync mode
no_match_contract = "(LibAGWTest|LibEVMTest)"

[profile.default.zksync]
enable_eravm_extensions = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
